### ISSUE TITLE
What adaptations should be made for other hands?

### ISSUE THREAD

**Issue by FrankLin9981** [wenbowen123/icra20-hand-object-pose#2]
Dear authors,

Thank you for sharing this amazing work!
From your README file, I find you mentions that it is possible to extend to many other hands.
I am curious about what adaptations should be made for other hands because I want to evaluate whether this method could be adopted in my system.

Sincerely,

Frank

**Comment by wenbowen123** [comment]
Hi, first you would need to change the paths to your hand's components in the yaml file. You would need to prepare for the .ply, .obj files for them. Also in current case of Yale Hand T42, there are 2 fingers which can only move horizontally in a plane. So during the PSO search, the fingers' possible motions are constrained by their DOF.  I would suggest to take a look at this [file ](https://github.com/wenbowen123/icra20-hand-object-pose/blob/master/src/perception/src/Hand.cpp). These are the things I could think of before seeing your particular hand. You can also email me about your particular case if you want.

**Comment by FrankLin9981** [comment]
Hello,

Thanks for your quick reply.
I will follow your suggestions and try my best to do these modifications firstly.
If I really can't figure out by myself, I may ask you for help.
Hope that won't bother you.

Sincerely,

Frank

**Comment by FrankLin9981** [comment]
Hello,

Sorry for bothering again.
I try to build up these packages by following your instruction, but it fails.
Error messages are shown in the following figure.
![image](https://user-images.githubusercontent.com/39838168/95148886-13f27b00-07b7-11eb-8e85-5903a620267e.png)
Have you ever encounter this problem?

BTW, to my knowledge, the default version of PCL in ROS kinetic is 1.7.
I install PCL 1.9 from source. But how to handle the version conflict issue properly.

Sincerely,

Frank

**Comment by wenbowen123** [comment]
Hi,
From the error, seems you are mixing PCL 1.7 and 1.9. I suggest you first uninstall 1.7. 
It should be safe to ignore ROS PCL. I never used ROS PCL, but install PCL separately.

**Comment by FrankLin9981** [comment]
Hello,
Do you mean that pcl_ros in find_package() of CMakeLists.txt can be ignored?

**Comment by wenbowen123** [comment]
Are you able to compile if removing the lines of "pcl_ros"?

**Comment by FrankLin9981** [comment]
I remove the "pcl_ros" and uninstall pcl 1.7.
However, it still fails. It seems that you use "pcl_ros" package in your codes. Take a look at the following screenshot.
![image](https://user-images.githubusercontent.com/39838168/95351658-0abaf880-08f4-11eb-9688-c15cbc56a8a2.png)

**Comment by wenbowen123** [comment]
sorry, the pcl_ros should be kept then. It seems you have installed PCL 1.7 to /usr. Please make sure only PCL 1.9 exists there.

**Comment by FrankLin9981** [comment]
Hi,
I still can't figure out how to build up this package.

**Comment by FrankLin9981** [comment]
Hello,
I finally build up the package with **PCL 1.7**. Then I want to try to run the example.
But I find that the files in Google Drive which are the [**object and hand CAD models, computed PPF features**](https://drive.google.com/file/d/1R1TGeIVTLngj-ju1-n3C7XDzLvS4lugd/view) is removed.
Could you share these files with me? Sorry to bother you!

Sincerely,

Frank

**Comment by wenbowen123** [comment]
Thanks for pointing this out. I have fixed the links.

**Comment by wenbowen123** [comment]
Seems the links were broken due to data rearrangement. Now it should be fixed. 
Close the issue for now. You can open new topics if you encounter other problems.
